dotfiles_dir = ".config/dotfiles"

[settings]
# Vars injected into dotfile templates
#vars = [ "vars.toml" ]

# An array of post install shell commands
#posthooks = [ "sway reload" ]

[settings.dots]
plasma-profile = { source = "env.sh", target = ".config/plasma-workspace/env/env.sh" }
git = { source = "gitconfig", target = ".config/git/config" }
fontconfig = { source = "fonts.conf", target = ".config/fontconfig/fonts.conf" }
vim = { source = "vimrc", target = ".vimrc" }
xcompose = { source = ".XCompose", target = ".XCompose" }

[profiles.linux.dots]
nushell-scripts = { source = "nushell/scripts", target = ".config/nushell/scripts" }
nushell-config = { source = "nushell/config.nu", target = ".config/nushell/config.nu" }
nushell-env = { source = "nushell/env.nu", target = ".config/nushell/env.nu" }
nushell-plugin = { source = "nushell/plugin.nu", target = ".config/nushell/plugin.nu" }

[profiles.macos.dots]
nushell-scripts = { source = "nushell/scripts", target = "Library/Application Support/nushell/scripts" }
nushell-config = { source = "nushell/config.nu", target = "Library/Application Support/nushell/config.nu" }
nushell-env = { source = "nushell/env.nu", target = "Library/Application Support/nushell/env.nu" }
nushell-plugin = { source = "nushell/plugin.nu", target = "Library/Application Support/nushell/plugin.nu" }

