# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# if prezto isn’t globally installed
test -z "$ZPREZTODIR" && source "$HOME/.zprezto/init.zsh"

test -f "$HOME/.zshrc_local" && source "$HOME/.zshrc_local"

# aliases
eval $(thefuck --alias)
alias cat='bat --paging=never'
alias less=bat
alias ls=exa
alias ll='exa -l --header --git --time-style=long-iso'
alias tree='exa --tree'
alias vim=nvim

alias pipup='pip3 list -o --format freeze | cut -d= -f1 | xargs pip3 install -U --user'

# queue stuff
alias slurmshell='ssh -qt vicb-submit-01 "srun -p icb_cpu -c 1 -t 01:00:00 --mem-per-cpu=1000 --pty bash"'


R() {
    if (( $# > 0 )); then
        /usr/bin/R "$@"
    else
        jupyter console --kernel=ir
    fi
}

# notify on long running commands
if [[ -f /usr/share/undistract-me/long-running.bash ]]; then
	source /usr/share/undistract-me/long-running.bash
	preexec_install() {
		# Just patch precmd instead of setting traps
		eval "$(whence -f precmd | sed '2ipreexec_set_exit')"
	}
	notify_when_long_running_commands_finish_install
fi

# command not found
test -f /usr/share/doc/pkgfile/command-not-found.zsh && source /usr/share/doc/pkgfile/command-not-found.zsh

# Secrets
# ssh-add </dev/null 2>/dev/null
# test -n "$SSH_ASKPASS" && export GITHUB_PAT=$("$SSH_ASKPASS" 'Password for "token flying-sheep@github.com"')
# circumvent libsecret bug until merge of https://gitlab.gnome.org/GNOME/libsecret/-/merge_requests/94
#gdbus call --session --dest org.freedesktop.secrets --object-path /org/freedesktop/secrets --method org.freedesktop.Secret.Service.SetAlias default /org/freedesktop/secrets/collection/kdewallet >/dev/null
#PYTHON_KEYRING_BACKEND=keyring.backends.SecretService.Keyring keyring get test test >/dev/null

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
